---
- name: Mail app to send verification emails
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_method: sudo
  tasks:
    - name: install nginx
      apt: name=postfix state=latest DEBIAN_PRIORITY=low
    - name: install node
      apt: name=nodejs state=latest
    - name: install npm
      apt: name=npm
    - name: upgrade npm
      command: npm install -g npm
    - name: Go to mailer and install npm packages
      command: chdir=../mailer npm install
    - name: Install PM2
      npm:
        name: pm2
        state: latest
        global: yes
    - name: Make PM2 start on startup
      command: env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
# Uncomment the following lines if you are on anything but OpenStack
# OpenStack creates some zombie for some reason
    # - name: Run PM@ 
    #   command: pm2 start mail-app.js